### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by Sjeff** [kabturek/monitor.sh#1]
Hi,

I would like to report an error.
```
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

Running Intel NUC i3
Ubuntu 18.04
Docker 18.09.0
Docker Compose 1.23.1

Looks like the file docker-entrypoint.sh can not be found.
If i build the image myself without : 
```
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
 ```
It seems to start the script.

Docker-compose file:
```
version: '3.7'
services:
  monitor.sh:
    image: kabturek/monitor.sh
    container_name: monitor.sh
    restart: always
    volumes: 
      - /srv/docker/monitor:/config
    network_mode: host
    cap_add:
      - NET_ADMIN
    command: bash monitor.sh -e -x -g -D /config
```

Best Regards,
Sjef
